### PR TITLE
feat: Add require ebs encryption scp

### PR DESCRIPTION
**Pull request by wavemoran**
## what

- Adds SCP to require EBS volume encryption

## why

- Encrypting EBS volumes is a good default security policy
- Seems like a common enough policy to include in the provided catalog

## references

- Shamelessly stolen from [Latacora's recommend policies](https://github.com/latacora/latacora-service-control-policies/blob/be35812a83a921e3582242c71ee977da6b7271ad/policy-groups/infrastructure-best-practices/main.tf#L30-L45)

### CODE REVIEW

**Comment by GabisCampana** [comment]
@goruha

**Review by goruha — APPROVED** [review]

**Pull request merged**
